
development:
  adapter: postgresql
  encoding: utf8
  database: review_site_8_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: review_site_8_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: review_site_8_production
  pool: 5
  username:
  password:

cucumber:
  <<: *TEST
